<?php

/**
 * @file
 * Contains drupal_ui_component.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_ui_component_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.drupal_ui_component':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal react components library') . '</p>';
      return $output;

    default:
  }
}
